# Generated by Django 2.0 on 2018-01-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='rank',
            field=models.CharField(default='indie', max_length=40),
        ),
    ]
