# Generated by Django 2.0 on 2018-01-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='users',
            field=models.ManyToManyField(to='shop.Player'),
        ),
    ]
