# Generated by Django 2.0 on 2018-01-11 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180111_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
                ('score', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='game',
            old_name='users',
            new_name='players',
        ),
        migrations.AddField(
            model_name='state',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Game'),
        ),
        migrations.AddField(
            model_name='state',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Player'),
        ),
    ]
