# Generated by Django 2.0 on 2018-01-13 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180111_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='transaction',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Game'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Player'),
        ),
    ]
