# Generated by Django 2.0 on 2018-01-17 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180113_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='paid_amount',
        ),
    ]
