# Generated by Django 2.0 on 2018-01-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20180123_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
