# Generated by Django 2.0 on 2018-01-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20180130_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
